server:
   port: 8201
   
  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
cloud:
 stream:
  bindings:
   input:
    destination: orgChangeTopic
    content-type: application/json
    group: licensingGroup
   binder:
    zkNodes: localhost
    brokers: localhost
 